### ISSUE TITLE
Bank Account Project

### ISSUE THREAD

**Issue by sabidhasan** [celkington/python#2]
I am opening an "issue" because it's the easiest way of commenting, and also because there is no need to do a full review again on `bank_account_project.py`. This is because it looks much, much better! Very impressed.

Few spacing/style issues, but this is something that comes with time, or by using a linter, which takes care of this for you.

Keep up the good work.

**Comment by celkington** [comment]
> I am opening an "issue" because it's the easiest way of commenting, and also because there is no need to do a full review again on `bank_account_project.py`. This is because it looks much, much better! Very impressed.
> 
> Few spacing/style issues, but this is something that comes with time, or by using a linter, which takes care of this for you.
> 
> Keep up the good work.

Thanks for taking the time to review my work. It's still very much early days in my Python journey so input from someone with much more experience such as yourself is incredibly valuable. Thank you Abid!
